CREATE TABLE posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand_id INTEGER REFERENCES brands(id) ON DELETE CASCADE NOT NULL,
    episode_number INTEGER NOT NULL,
    episode_title TEXT NOT NULL,
    episode_link TEXT NOT NULL,
    campaign TEXT NOT NULL,
    pr_link TEXT
);