BEGIN;

TRUNCATE
posts,
brands
RESTART IDENTITY CASCADE;

INSERT INTO brands (brand_name)
VALUES
('4 Rivers Smokehouse'),
('7-Eleven'),
('A&W'),
('Applebee''s'),
('Arby''s'),
('Bang Energy'),
('Baskin Robbins'),
('Bojangles'),
('Booster Juice'),
('Boston Market'),
('Boston''s Pizza'),
('Burger King'),
('BurgerFi'),
('Carl''s Jr'),
('Checker''s and Rally''s'),
('Cheez-It'),
('Chick-fil-A'),
('Chicken Guy'),
('Chipotle'),
('Chuck E. Cheese'),
('Cinnabon'),
('Cold Stone Creamery'),
('Coolgreens'),
('CoreLife Eatery'),
('Dairy Queen'),
('Denny''s'),
('Domino''s'),
('Doritos'),
('Duck Donuts'),
('Dunkin'''),
('Earl of Sandwich'),
('Edible Arrangements'),
('Einstein Bros Bagles'),
('Fancy Feast'),
('Fatburger'),
('Fazoli''s'),
('Fresh & Co'),
('GarfieldEATS'),
('Hardee''s'),
('Heinz'),
('Jack in the Box'),
('Jelly Belly'),
('Jersey Mike''s'),
('Jester''s'),
('KFC'),
('Kraft'),
('Krispy Kreme'),
('Krystal'),
('Marks & Spencer'),
('McDonald''s'),
('Michael Jordan''s Steakhouse'),
('Mickey''s Deli'),
('MTN DEW'),
('Next Level Burger'),
('Olive Garden'),
('Oreo'),
('Panera Bread'),
('Papa John''s'),
('PDQ'),
('Pepsi'),
('Perverted Ice Cream'),
('Pizza Hut'),
('Pizza Inn'),
('Planters'),
('Popeyes'),
('Poptarts'),
('Pringles'),
('Red Lobster'),
('Reese''s'),
('Regal Cinema'),
('Sonic'),
('Sour Patch Kids'),
('Spangles'),
('Starbucks'),
('Stonefire Grill'),
('Subway'),
('Sweet Frog'),
('Taco Bell'),
('The Hummus & Pita Co.'),
('Tim Horton''s'),
('Toppers Pizza'),
('Tropical Smoothie'),
('Vampire Pizza'),
('Wendy''s'),
('Whataburger'),
('White Castle'),
('Wienerschnitzel'),
('Yogurtland'),
('Your Pie'),
('Zaxby''s');

INSERT INTO posts (brand_id, episode_number, episode_title, episode_link, campaign, pr_link)
VALUES
--Template (int, int, 'str', 'str', 'str', 'str/null'),
(78, 304, 'Chicken Soup for Boys', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-304-chicken-soup-boys/', 'Naked Crispy Chicken Taco', null),
(84, 305, 'Bubble Jug Life', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-305-bubble-jug-life/', 'Bacon Mozzarella Burger', 'https://www.prnewswire.com/news-releases/wendys-releases-its-next-hit-single---the-bacon-mozzarella-burger-300273853.html'),
(55, 306, 'Face 2 Face: Foggy Bottoms', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-306-face-2-face-foggy-bottoms/', 'BreadStick Sandwhiches and Deep Dish Spaghetti Pies', 'str/null', 'https://www.prnewswire.com/news-releases/olive-garden-unveils-new-breadstick-sandwiches-and-deep-dish-spaghetti-pies-300274598.html'),
(12, 309, 'Here Comes Ray Donovan', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-309-here-comes-ray-donovan/', 'Burger Mac n'' Cheetos', 'https://www.businesswire.com/news/home/20160627005012/en/BURGER-KING%C2%AE-Restaurants-CHEETOS%C2%AE-Brand-Unleash-Cheesy'),
(27, 312, 'Face 2 Face: Live from Drowzee City', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-312-face-2-face-live-drowzee-city/', 'Burger Pizza', null),
(27, 321, 'Which One Vapes?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-321-which-one-vapes/', 'Salads', 'https://www.prnewswire.com/news-releases/dominos-launches-salads-nationwide-300313050.html'),
(62, 322, '"Margaret, It Happened Again!"', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-322-margaret-it-happened-again/', 'Grilled Cheese Stuffed Pizza', 'https://blog.pizzahut.com/this-is-not-a-drill-pizza-hut-unleashes-latest-cheesy-goodness-in-all-new-grilled-cheese-stuffed-crust-pizza/'),
(41, 324, 'A Heroic and Well-Reviewed Lizard', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-324-heroic-and-well-reviewed-lizard/', 'Brunchfast Menu', null),
(84, 326, 'Open-Source Burger King', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-326-open-source-burger-king/', 'Taco Salad', 'https://www.prnewswire.com/news-releases/wendys-tacolicious-taco-salad-makes-its-long-awaited-comeback-300338877.html'),
(14, 328, 'The Anxiety Free Cruise', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-328-anxiety-free-cruise/', 'Beer Cheese Bacon Burger', 'https://www.businesswire.com/news/home/20161027005248/en/Carl%E2%80%99s-Jr.-Hardee%E2%80%99s-Introduce-Budweiser-Beer-Cheese'),
(84, 336, 'Twenty-Something-Teen', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-336-twenty-something-teen/', 'Spicy Chicken Sandwich', 'https://www.irwendys.com/news/news-details/2016/Wendys-New-Spicy-Sriracha-Chicken-Sandwich-Takes-Sriracha-To-A-New-Level/default.aspx'),
(78, 340, 'Doritos-Blasted Crow', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-340-doritos-blasted-crow/', 'Naked Chicken Chalupa', null),
(28, 345, 'Face 2 Face: Candlenights in September', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-345-face-2-face-candlenights-september/', 'Boldest Choice Campaign', 'https://www.prnewswire.com/news-releases/doritos-rocks-election-season-to-empower-young-voters-300333737.html'),
(44, 349, 'Face 2 Face: Remembering How do Do Live Shows in Portland', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-349-face-2-face-remembering-how-do-live-shows-portland/', 'Chicken Parm Parmi Pie', 'https://www.perthnow.com.au/community-news/weekend-kwinana-courier/waikiki-womans-chicken-parmi-pie-gets-a-go-at-jesters-c-802844'),
(78, 351, 'Omnidirectional Scampi Blast', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-351-omnidirectional-scampi-blast/', 'Nacho Fries', null),
(78, 354, 'Beanfreak', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-354-beanfreak/', 'Naked Chicken Chips', 'https://www.prnewswire.com/news-releases/naked-chicken-is-making-a-comeback-at-taco-bell-and-its-a-chip-off-the-ol-chalupa-300451121.html'),
(50, 356, 'Face 2 Face: My Donut-Loving Boys', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-356-face-2-face-my-donut-loving-boys/', '"Artisanal" Sanwhiches', 'https://www.usatoday.com/story/money/2017/05/15/no-your-not-panera-mcdonalds-goes-artisanal-fancy-sandwiches/101606472/'),
(14, 357, 'A Wonderful Hug From Goro', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-357-wonderful-hug-goro/', 'Baby Back Rib Burger', 'https://www.businesswire.com/news/home/20170413006150/en/Carl%E2%80%99s-Jr.-Hardee%E2%80%99s-Pioneer-Greatest-American-Burgerl'),
(5, 358, 'Detective Jigsaw, My Very Best Friend', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-358-detective-jigsaw-my-very-best-friend/', 'Smokehouse Pork Belly Sandwhich', 'https://www.businesswire.com/news/home/20170501005759/en/It%E2%80%99s-%E2%80%93-Smokehouse-Pork-Belly-Sandwich-Returns'),
(80, 363, 'Breathing in Space', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-363-breathing-space/', '150th Canadian Anniversary Menu', 'https://www.businesswire.com/news/home/20170628005270/en/Celebrate-Canada%E2%80%99s-150th-Anniversary-New-Canadian-Inspired'),
(4, 364, 'Face 2 Face: Dumbledore''s Magic Buffalo Wings', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-364-face-2-face-dumbledores-magic-buffalo-wings/', 'Topped and Loaded Menu', 'https://www.prnewswire.com/news-releases/applebees-introduces-new-topped--loaded-menu-starting-at-only-1099-300484793.html'),
(8, 369, 'Independence Jumanji 3', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-396-independence-jumanji-3/', 'Heart-Shaped Bo-Berry Biscuits', 'https://www.qsrmagazine.com/news/heart-shaped-bo-berry-biscuits-and-more-bojangles-v-day'),
(88, 372, 'Face 2 Face: Sock-Based Target Crimes', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-372-face-2-face-sock-based-target-crimes/', 'Chocolate and Vanilla Ice Cream', 'https://www.qsrmagazine.com/news/yogurtlands-ice-cream-has-been-hit-fans'),
(50, 374, 'Respect the Journey', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-374-respect-journey/', 'Buttermilk Crispy Chicken Tenders & Art Posters', 'https://www.qsrmagazine.com/news/mcdonalds-introduces-buttermilk-crispy-tenders-art-posters'),
(85, 375, 'Massage Drone Switcheroo', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-375-massage-drone-switcheroo/', 'Chorizo Burger', 'https://www.qsrmagazine.com/news/whataburger-launches-chorizo-burger-and-chorizo-taquito'),
(78, 376, 'Face 2 Face: Shrimp, Heaven, Live!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-376-face-2-face-shrimp-heaven-live/', 'Naked Egg Taco', 'https://www.prnewswire.com/news-releases/taco-bell-turns-breakfast-inside-out-with-naked-egg-taco-debuting-on-august-31-300504273.html'),
(67, 382, 'The Craw Daddy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-382-craw-daddy/', 'Thanksgiving Dinner', null),
(21, 384, 'Face 2 Face: TORONTO! LISTEN!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-384-face-2-face-toronto-listen/', 'Cookie BonBite', 'https://www.prnewswire.com/news-releases/cinnabon-debuts-new-cookie-bonbite-for-national-cookie-day-300564502.html'),
(77, 385, 'Horses in the Drift', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-385-horses-drift/', '"Deck the Halls" Christmas Spectacle', 'https://www.sweetfrog.com/pressroom/2017/swf-121217-deck-the-halls-christmas-spectacle-returns-to-sweetfrog-frozen-yogurt.php'),
(70, 386, 'Candlenights 2017', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-candlenights-2017/', 'Cheetos Popcorn', 'https://movieweb.com/cheetos-flavored-popcorn-regal-cinemas/'),
(33, 392, 'Big Game Tony Sunday', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-392-big-game-tony-sunday/', 'Wake Up to Bagels Campaign', 'https://www.prnewswire.com/news-releases/einstein-bros-bagels-replaces-traditional-alarm-clock-sounds-with-breakfast-themed-wake-up-tones-300577592.html'),
(55, 392, 'Big Game Tony Sunday', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-392-big-game-tony-sunday/', 'Loaded Pasta Chips', null),
(12, 394, 'Face 2 Face: I Fritos Hard', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-394-face-2-face-i-fritos-hard/', 'Whopper Severance Package', 'https://www.businesswire.com/news/home/20170829005114/en'),
(78, 394, 'Face 2 Face: I Fritos Hard', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-394-face-2-face-i-fritos-hard/', 'Forever 21 Campaign', 'https://www.prnewswire.com/news-releases/taco-bell--forever-21-are-making-wardrobes-a-whole-lot-saucier-this-fall-300527287.html'),
(90, 401, 'Max Cooljazz', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-401-max-cooljazz/', 'Zensation Salad', 'https://www.qsrmagazine.com/news/zensation-zalad-returns-zaxbys-limited-time'),
(25, 406, 'Face 2 Face: Sweet Dreams, Timothy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-406-face-2-face-sweet-dreams-timothy/', 'Summer Blizzard Treat Menu', 'https://www.businesswire.com/news/home/20180503006216/en'),
(50, 408, 'Come and Get It!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-408-come-and-get-it/', '"That''s the MIX" Campaign', 'https://www.qsrmagazine.com/news/launches-exclusive-sprite-tropic-berry-drink'),
(36, 410, 'Game Man', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-410-game-man/', 'Breadstick Sliders', 'https://www.qsrmagazine.com/news/fazoli-s-adds-breadstick-sliders-indianapolis-national-launch-next'),
(27, 411, 'Face 2 Face: Bon Voyage!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-411-face-2-face-bon-voyage/', '"Paving for Pizza" Campaign', 'https://www.prnewswire.com/news-releases/dont-let-bad-potholes-ruin-good-pizza-dominos-starts-paving-for-pizza-300662508.html'),
(30, 413, 'Faster Car', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-413-faster-car/', 'Donut Fries', 'https://news.dunkindonuts.com/news/releases-20180626'),
(79, 415, 'My Very Cool Telescope!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-415-my-very-cool-telescope/', 'Hummus Ice Cream', 'https://www.qsrmagazine.com/news/hummus-pita-co-prepares-launch-hummus-ice-cream'),
(17, 417, 'DVDs For the People', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-417-dvds-people/', 'Meal Kits', 'https://thechickenwire.chick-fil-a.com/news/chick-fil-as-hometown-customers-get-first-opportunity-to-try-new-mealkits-concept'),
(30, 427, 'Face 2 Face: Adult Big Green Reptiles', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-427-face-2-face-adult-big-green-reptiles/', 'Dunkin` Donuts rebrands to Dunkin`', 'https://news.dunkindonuts.com/news/releases-20180925'),
(23, 428, 'Big Debbie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-428-big-debbie/', 'Nothing, Justin just likes the name', 'https://markets.businessinsider.com/news/stocks/coolgreens-brings-on-franchise-veteran-executive-as-new-vice-president-of-operations-1027583819'),
(25, 428, 'Big Debbie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-428-big-debbie/', 'DQ Fall Menu', 'https://www.qsrmagazine.com/news/dairy-queen-unveils-first-fall-blizzard-menu-including-snickerdoodle-cookie-dough'),
(52, 429, 'Lactating Las Vegas', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-429-lactating-las-vegas/', 'Spooky Cheeto Pizza', 'https://www.qsrmagazine.com/news/mickeys-creates-spicy-spooky-cheeto-pizza'),
(12, 431, 'A Very Spooky Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-431-very-spooky-burger/', 'Nightmare King', 'https://www.businesswire.com/news/home/20181017005208/en/BURGER-KING%C2%AE-Brand-Creates-Halloween-Sandwich-Clinically'),
(12, 431, 'A Very Spooky Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-431-very-spooky-burger/', 'Philly Cheese King sold at all but 1 BK', 'https://www.businesswire.com/news/home/20181025005134/en/BURGER-KING%C2%AE-Launches-PHILLY-CHEESE-KING%C2%AE-Nationwide'),
(12, 437, 'A Silent Chug', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-437-silent-chug/', 'Dogpper', 'https://www.qsrmagazine.com/news/burger-king-introduces-dogpper-dog-bone-flame-grilled-taste'),
(12, 437, 'A Silent Chug', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-437-silent-chug/', 'Whopper Detour', 'https://www.qsrmagazine.com/burgers/bk-whoppers-are-only-1-cent-when-you-order-mcdonalds'),
--Template (int, int, 'str', 'str', 'str', 'str/null'),
(12, 437, 'A Silent Chug', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-437-silent-chug/', 'WHOPPER-SHOPPER.com', 'https://www.qsrmagazine.com/news/burger-king-makes-other-brands-pay-your-whopper'),
(71, 438, 'Face 2 Face: The Ham Up There', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-438-face-2-face-ham-up-there/', 'Fritos Chili Cheese Fries', 'https://www.qsrmagazine.com/news/sonic-adds-fritos-chili-cheese-faves-starting-99-cents'),
(7, 441, 'In A New York Whoopsie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-441-new-york-whoopsie/', 'Brownie-Inspired Flavors', 'https://www.qsrmagazine.com/news/baskin-robbins-adds-new-brownie-inspired-flavors-menu'),
(24, 441, 'In a New York Whoopsie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-441-new-york-whoopsie/', 'Tim Tebow Food Revolution', 'https://www.qsrmagazine.com/news/tim-tebow-teams-corelife-eatery-food-revolution'),
(47, 444, 'The 100 Wishes of the Pandemonium Cube', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-444-100-wishes-pandemonium-cube/', '#SayItWithDonuts', 'https://www.qsrmagazine.com/news/krispy-kreme-introduces-line-valentine-conversation-heart-doughnuts'),
(8, 445, 'Pizzalicious Turbo-Moths', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-445-pizzalicious-turbo-moths/', '50-Piece Chicken Supremes', 'https://www.bojangles.com/news/press-releases/bojangles-adds-mvp-before-this-sundays-big-game/'),
(84, 446, 'Face 2 Face: The Cupture', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-446-face-2-face-cupture/', 'Made To Crave Cheeseburgers', 'https://www.prnewswire.com/news-releases/wendys-beefs-up-its-menu-with-three-new-made-to-crave-cheeseburgers-300788539.html'),
(27, 447, 'Valentine''s Escape Room', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-447-valentines-escape-room/', '"Points for Pies" Programs', 'https://www.qsrmagazine.com/pizza/dominos-new-platform-rewards-points-competitors-pizza'),
(50, 447, 'Valentine''s Escape Room', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-447-valentines-escape-room/', 'Donut Sticks', 'https://www.qsrmagazine.com/news/adds-donut-sticks-breakfast-lineup'),
(76, 450, 'Face 2 Face: The Emoji Contract', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-450-face-2-face-emoji-contract/', 'Ultimate Cheesy Garlic Bread Challenge ft. The Bachelor contestants', 'qsrmagazine.com/news/stars-bachelor-love-subway-s-new-ultimate-cheesy-garlic-bread'),
(18, 451, 'Spider-Man''s Magic Potion', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-451-spider-mans-magic-potion/', 'Guy Fieri Chicken Resturaunt', 'https://www.qsrmagazine.com/news/guy-fieri-s-chicken-guy-restaurant-open-miami'),
(62, 452, 'The Cornbread Heist of the Century', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-452-cornbread-heist-century/', 'P''Zone', 'https://www.qsrmagazine.com/news/pizza-hut-brings-back-cult-favorite-p-zone-march-madness'),
