BEGIN;

TRUNCATE
posts,
brands
RESTART IDENTITY CASCADE;

INSERT INTO brands (brand_name)
VALUES
('4 Rivers Smokehouse'),
('7-Eleven'),
('A&W'),
('Applebee''s'),
('Arby''s'),
('Bang Energy'),
('Baskin Robbins'),
('Bojangles'),
('Booster Juice'),
('Boston Market'),
('Boston''s Pizza'),
('Burger King'),
('BurgerFi'),
('Carl''s Jr'),
('Checker''s and Rally''s'),
('Cheez-It'),
('Chick-fil-A'),
('Chicken Guy'),
('Chipotle'),
('Chuck E. Cheese'),
('Cinnabon'),
('Cold Stone Creamery'),
('Coolgreens'),
('CoreLife Eatery'),
('Dairy Queen'),
('Denny''s'),
('Domino''s'),
('Doritos'),
('Duck Donuts'),
('Dunkin'''),
('Earl of Sandwich'),
('Edible Arrangements'),
('Einstein Bros Bagles'),
('Fancy Feast'),
('Fatburger'),
('Fazoli''s'),
('Fresh & Co'),
('GarfieldEATS'),
('Hardee''s'),
('Heinz'),
('Jack in the Box'),
('Jelly Belly'),
('Jersey Mike''s'),
('Jester''s'),
('KFC'),
('Kraft'),
('Krispy Kreme'),
('Krystal'),
('Marks & Spencer'),
('McDonald''s'),
('Michael Jordan''s Steakhouse'),
('Mickey''s Deli'),
('MTN DEW'),
('Next Level Burger'),
('Olive Garden'),
('Oreo'),
('Panera Bread'),
('Papa John''s'),
('PDQ'),
('Pepsi'),
('Perverted Ice Cream'),
('Pizza Hut'),
('Pizza Inn'),
('Planters'),
('Popeyes'),
('Poptarts'),
('Pringles'),
('Red Lobster'),
('Reese''s'),
('Regal Cinema'),
('Sonic'),
('Sour Patch Kids'),
('Spangles'),
('Starbucks'),
('Stonefire Grill'),
('Subway'),
('Sweet Frog'),
('Taco Bell'),
('The Hummus & Pita Co.'),
('Tim Horton''s'),
('Toppers Pizza'),
('Tropical Smoothie'),
('Vampire Pizza'),
('Wendy''s'),
('Whataburger'),
('White Castle'),
('Wienerschnitzel'),
('Yogurtland'),
('Your Pie'),
('Zaxby''s');

INSERT INTO posts(brand_id, episode_number, episode_title, episode_link, campaign, pr_link)
VALUES
(78, 304, 'Chicken Soup for Boys', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-304-chicken-soup-boys/', 'Naked Crispy Chicken Taco', 'null'),
(84, 305, 'Bubble Jug Life', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-305-bubble-jug-life/', 'Bacon Mozzarella Burger', 'https://www.prnewswire.com/news-releases/wendys-releases-its-next-hit-single---the-bacon-mozzarella-burger-300273853.html'),
(55, 306, 'Face 2 Face: Foggy Bottoms', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-306-face-2-face-foggy-bottoms/', 'BreadStick Sandwhiches and Deep Dish Spaghetti Pies', 'https://www.prnewswire.com/news-releases/olive-garden-unveils-new-breadstick-sandwiches-and-deep-dish-spaghetti-pies-300274598.html'),
(12, 309, 'Here Comes Ray Donovan', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-309-here-comes-ray-donovan/', 'Burger Mac n'' Cheetos', 'https://www.businesswire.com/news/home/20160627005012/en/BURGER-KING%C2%AE-Restaurants-CHEETOS%C2%AE-Brand-Unleash-Cheesy'),
(27, 312, 'Face 2 Face: Live from Drowzee City', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-312-face-2-face-live-drowzee-city/', 'Burger Pizza ', 'null'),
(27, 321, 'Which One Vapes?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-321-which-one-vapes/', 'Salads', 'https://www.prnewswire.com/news-releases/dominos-launches-salads-nationwide-300313050.html'),
(62, 322, '"Margaret, It Happened Again!"', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-322-margaret-it-happened-again/', 'Grilled Cheese Stuffed Pizza', 'https://blog.pizzahut.com/this-is-not-a-drill-pizza-hut-unleashes-latest-cheesy-goodness-in-all-new-grilled-cheese-stuffed-crust-pizza/'),
(41, 324, 'A Heroic and Well-Reviewed Lizard', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-324-heroic-and-well-reviewed-lizard/', 'Brunchfast Menu', 'null'),
(84, 326, 'Open-Source Burger King', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-326-open-source-burger-king/', 'Taco Salad', 'https://www.prnewswire.com/news-releases/wendys-tacolicious-taco-salad-makes-its-long-awaited-comeback-300338877.html'),
(14, 328, 'The Anxiety Free Cruise', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-328-anxiety-free-cruise/', 'Beer Cheese Bacon Burger', 'https://www.businesswire.com/news/home/20161027005248/en/Carl%E2%80%99s-Jr.-Hardee%E2%80%99s-Introduce-Budweiser-Beer-Cheese'),
(84, 336, 'Twenty-Something-Teen', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-336-twenty-something-teen/', 'Spicy Chicken Sandwich', 'https://www.irwendys.com/news/news-details/2016/Wendys-New-Spicy-Sriracha-Chicken-Sandwich-Takes-Sriracha-To-A-New-Level/default.aspx'),
(78, 340, 'Doritos-Blasted Crow', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-340-doritos-blasted-crow/', 'Naked Chicken Chalupa', 'null'),
(28, 345, 'Face 2 Face: Candlenights in September', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-345-face-2-face-candlenights-september/', 'Boldest Choice Campaign', 'https://www.prnewswire.com/news-releases/doritos-rocks-election-season-to-empower-young-voters-300333737.html'),
(44, 349, 'Face 2 Face: Remembering How do Do Live Shows in Portland', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-349-face-2-face-remembering-how-do-live-shows-portland/', 'Chicken Parm Parmi Pie', 'https://www.perthnow.com.au/community-news/weekend-kwinana-courier/waikiki-womans-chicken-parmi-pie-gets-a-go-at-jesters-c-802844'),
(78, 351, 'Omnidirectional Scampi Blast', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-351-omnidirectional-scampi-blast/', 'Nacho Fries', 'null'),
(78, 354, 'Beanfreak', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-354-beanfreak/', 'Naked Chicken Chips', 'https://www.prnewswire.com/news-releases/naked-chicken-is-making-a-comeback-at-taco-bell-and-its-a-chip-off-the-ol-chalupa-300451121.html'),
(50, 356, 'Face 2 Face: My Donut-Loving Boys', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-356-face-2-face-my-donut-loving-boys/', '"Artisanal" Sanwhiches', 'https://www.usatoday.com/story/money/2017/05/15/no-your-not-panera-mcdonalds-goes-artisanal-fancy-sandwiches/101606472/'),
(14, 357, 'A Wonderful Hug From Goro', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-357-wonderful-hug-goro/', 'Baby Back Rib Burger', 'https://www.businesswire.com/news/home/20170413006150/en/Carl%E2%80%99s-Jr.-Hardee%E2%80%99s-Pioneer-Greatest-American-Burger'),
(5, 358, 'Detective Jigsaw, My Very Best Friend', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-358-detective-jigsaw-my-very-best-friend/', 'Smokehouse Pork Belly Sandwhich', 'https://www.businesswire.com/news/home/20170501005759/en/It%E2%80%99s-%E2%80%93-Smokehouse-Pork-Belly-Sandwich-Returns'),
(80, 363, 'Breathing in Space', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-363-breathing-space/', '150th Canadian Anniversary Menu', 'https://www.businesswire.com/news/home/20170628005270/en/Celebrate-Canada%E2%80%99s-150th-Anniversary-New-Canadian-Inspired'),
(4, 364, 'Face 2 Face: Dumbledore''s Magic Buffalo Wings', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-364-face-2-face-dumbledores-magic-buffalo-wings/', 'Topped and Loaded Menu', 'https://www.prnewswire.com/news-releases/applebees-introduces-new-topped--loaded-menu-starting-at-only-1099-300484793.html'),
(8, 369, 'Independence Jumanji 3', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-396-independence-jumanji-3/', 'Heart-Shaped Bo-Berry Biscuits', 'https://www.qsrmagazine.com/news/heart-shaped-bo-berry-biscuits-and-more-bojangles-v-day'),
(88, 372, 'Face 2 Face: Sock-Based Target Crimes', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-372-face-2-face-sock-based-target-crimes/', 'Chocolate and Vanilla Ice Cream', 'https://www.qsrmagazine.com/news/yogurtlands-ice-cream-has-been-hit-fans'),
(50, 374, 'Respect the Journey', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-374-respect-journey/', 'Buttermilk Crispy Chicken Tenders & Art Posters', 'https://www.qsrmagazine.com/news/mcdonalds-introduces-buttermilk-crispy-tenders-art-posters'),
(85, 375, 'Massage Drone Switcheroo', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-375-massage-drone-switcheroo/', 'Chorizo Burger', 'https://www.qsrmagazine.com/news/whataburger-launches-chorizo-burger-and-chorizo-taquito'),
(78, 376, 'Face 2 Face: Shrimp, Heaven, Live!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-376-face-2-face-shrimp-heaven-live/', 'Naked Egg Taco', 'https://www.prnewswire.com/news-releases/taco-bell-turns-breakfast-inside-out-with-naked-egg-taco-debuting-on-august-31-300504273.html'),
(67, 382, 'The Craw Daddy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-382-craw-daddy/', 'Thanksgiving Dinner', 'null'),
(21, 384, 'Face 2 Face: TORONTO! LISTEN!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-384-face-2-face-toronto-listen/', 'Cookie BonBite', 'https://www.prnewswire.com/news-releases/cinnabon-debuts-new-cookie-bonbite-for-national-cookie-day-300564502.html'),
(77, 385, 'Horses in the Drift', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-385-horses-drift/', '"Deck the Halls" Christmas Spectacle', 'https://www.sweetfrog.com/pressroom/2017/swf-121217-deck-the-halls-christmas-spectacle-returns-to-sweetfrog-frozen-yogurt.php'),
(70, 386, 'Candlenights 2017', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-candlenights-2017/', 'Cheetos Popcorn', 'https://movieweb.com/cheetos-flavored-popcorn-regal-cinemas/'),
(33, 392, 'Big Game Tony Sunday', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-392-big-game-tony-sunday/', 'Wake Up to Bagels Campaign', 'https://www.prnewswire.com/news-releases/einstein-bros-bagels-replaces-traditional-alarm-clock-sounds-with-breakfast-themed-wake-up-tones-300577592.html'),
(55, 392, 'Big Game Tony Sunday', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-392-big-game-tony-sunday/', 'Loaded Pasta Chips', 'null'),
(12, 394, 'Face 2 Face: I Fritos Hard', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-394-face-2-face-i-fritos-hard/', 'Whopper Severance Package', 'https://www.businesswire.com/news/home/20170829005114/en'),
(78, 394, 'Face 2 Face: I Fritos Hard', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-394-face-2-face-i-fritos-hard/', 'Forever 21 Campaign', 'https://www.prnewswire.com/news-releases/taco-bell--forever-21-are-making-wardrobes-a-whole-lot-saucier-this-fall-300527287.html'),
(90, 401, 'Max Cooljazz', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-401-max-cooljazz/', 'Zensation Salad', 'https://www.qsrmagazine.com/news/zensation-zalad-returns-zaxbys-limited-time'),
(25, 406, 'Face 2 Face: Sweet Dreams, Timothy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-406-face-2-face-sweet-dreams-timothy/', 'Summer Blizzard Treat Menu', 'https://www.businesswire.com/news/home/20180503006216/en'),
(50, 408, 'Come and Get It!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-408-come-and-get-it/', '"That''s the MIX" Campaign', 'https://www.qsrmagazine.com/news/launches-exclusive-sprite-tropic-berry-drink'),
(36, 410, 'Game Man', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-410-game-man/', 'Breadstick Sliders', 'https://www.qsrmagazine.com/news/fazoli-s-adds-breadstick-sliders-indianapolis-national-launch-next'),
(27, 411, 'Face 2 Face: Bon Voyage!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-411-face-2-face-bon-voyage/', '"Paving for Pizza" Campaign', 'https://www.prnewswire.com/news-releases/dont-let-bad-potholes-ruin-good-pizza-dominos-starts-paving-for-pizza-300662508.html'),
(30, 413, 'Faster Car', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-413-faster-car/', 'Donut Fries', 'https://news.dunkindonuts.com/news/releases-20180626'),
(79, 415, 'My Very Cool Telescope!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-415-my-very-cool-telescope/', 'Hummus Ice Cream', 'https://www.qsrmagazine.com/news/hummus-pita-co-prepares-launch-hummus-ice-cream'),
(17, 417, 'DVDs For the People', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-417-dvds-people/', 'Meal Kits', 'https://thechickenwire.chick-fil-a.com/news/chick-fil-as-hometown-customers-get-first-opportunity-to-try-new-mealkits-concept'),
(19, 422, 'The Very Best Stains', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-422-very-best-stains/', 'Testing Bacon', 'https://www.qsrmagazine.com/menu-innovations/chipotle-start-testing-bacon-september'),
(30, 427, 'Face 2 Face: Adult Big Green Reptiles', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-427-face-2-face-adult-big-green-reptiles/', 'Dunkin` Donuts rebrands to Dunkin`', 'https://news.dunkindonuts.com/news/releases-20180925'),
(23, 428, 'Big Debbie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-428-big-debbie/', 'Nothing, Justin just likes the name', 'https://markets.businessinsider.com/news/stocks/coolgreens-brings-on-franchise-veteran-executive-as-new-vice-president-of-operations-1027583819'),
(25, 428, 'Big Debbie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-428-big-debbie/', 'DQ Fall Menu', 'https://www.qsrmagazine.com/news/dairy-queen-unveils-first-fall-blizzard-menu-including-snickerdoodle-cookie-dough'),
(52, 429, 'Lactating Las Vegas', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-429-lactating-las-vegas/', 'Spooky Cheeto Pizza', 'https://www.qsrmagazine.com/news/mickeys-creates-spicy-spooky-cheeto-pizza'),
(12, 431, 'A Very Spooky Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-431-very-spooky-burger/', 'Nightmare King', 'https://www.businesswire.com/news/home/20181017005208/en/BURGER-KING%C2%AE-Brand-Creates-Halloween-Sandwich-Clinically'),
(12, 431, 'A Very Spooky Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-431-very-spooky-burger/', 'Philly Cheese King sold at all but 1 BK', 'https://www.businesswire.com/news/home/20181025005134/en/BURGER-KING%C2%AE-Launches-PHILLY-CHEESE-KING%C2%AE-Nationwide'),
(12, 437, 'A Silent Chug', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-437-silent-chug/', 'Dogpper', 'https://www.qsrmagazine.com/news/burger-king-introduces-dogpper-dog-bone-flame-grilled-taste'),
(12, 437, 'A Silent Chug', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-437-silent-chug/', 'Whopper Detour', 'https://www.qsrmagazine.com/burgers/bk-whoppers-are-only-1-cent-when-you-order-mcdonalds'),
(12, 437, 'A Silent Chug', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-437-silent-chug/', 'WHOPPER-SHOPPER.com', 'https://www.qsrmagazine.com/news/burger-king-makes-other-brands-pay-your-whopper'),
(71, 438, 'Face 2 Face: The Ham Up There', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-438-face-2-face-ham-up-there/', 'Fritos Chili Cheese Fries', 'https://www.qsrmagazine.com/news/sonic-adds-fritos-chili-cheese-faves-starting-99-cents'),
(7, 441, 'In A New York Whoopsie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-441-new-york-whoopsie/', 'Brownie-Inspired Flavors', 'https://www.qsrmagazine.com/news/baskin-robbins-adds-new-brownie-inspired-flavors-menu'),
(24, 441, 'In a New York Whoopsie', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-441-new-york-whoopsie/', 'Tim Tebow Food Revolution', 'https://www.qsrmagazine.com/news/tim-tebow-teams-corelife-eatery-food-revolution'),
(47, 444, 'The 100 Wishes of the Pandemonium Cube', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-444-100-wishes-pandemonium-cube/', '#SayItWithDonuts', 'https://www.qsrmagazine.com/news/krispy-kreme-introduces-line-valentine-conversation-heart-doughnuts'),
(8, 445, 'Pizzalicious Turbo-Moths', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-445-pizzalicious-turbo-moths/', '50-Piece Chicken Supremes', 'https://www.bojangles.com/news/press-releases/bojangles-adds-mvp-before-this-sundays-big-game/'),
(84, 446, 'Face 2 Face: The Cupture', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-446-face-2-face-cupture/', 'Made To Crave Cheeseburgers', 'https://www.prnewswire.com/news-releases/wendys-beefs-up-its-menu-with-three-new-made-to-crave-cheeseburgers-300788539.html'),
(27, 447, 'Valentine''s Escape Room', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-447-valentines-escape-room/', '"Points for Pies" Programs', 'https://www.qsrmagazine.com/pizza/dominos-new-platform-rewards-points-competitors-pizza'),
(50, 447, 'Valentine''s Escape Room', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-447-valentines-escape-room/', 'Donut Sticks', 'https://www.qsrmagazine.com/news/adds-donut-sticks-breakfast-lineup'),
(76, 450, 'Face 2 Face: The Emoji Contract', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-450-face-2-face-emoji-contract/', 'Ultimate Cheesy Garlic Bread Challenge ft. The Bachelor contestants', 'qsrmagazine.com/news/stars-bachelor-love-subway-s-new-ultimate-cheesy-garlic-bread'),
(18, 451, 'Spider-Man''s Magic Potion', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-451-spider-mans-magic-potion/', 'Guy Fieri Chicken Resturaunt', 'https://www.qsrmagazine.com/news/guy-fieri-s-chicken-guy-restaurant-open-miami'),
(62, 452, 'The Cornbread Heist of the Century', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-452-cornbread-heist-century/', 'P''Zone', 'https://www.qsrmagazine.com/news/pizza-hut-brings-back-cult-favorite-p-zone-march-madness'),
(14, 453, 'The Grotto of Gains', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-453-grotto-gains/', 'Bacon Truffle Burger and Bacon Truffle Fries', 'https://www.businesswire.com/news/home/20190327005220/en/Carl%E2%80%99s-Jr.%C2%AE-Launches-New-Bacon-Truffle-Angus'),
(30, 453, 'The Grotto of Gains', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-453-grotto-gains/', 'Peeps Coffee and Peeps Donut', 'https://news.dunkindonuts.com/news/hop-into-spring-at-dunkin-with-new-peepsR-marshmallow-flavored-coffee-and-peepsR-donut'),
(2, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Avocado Toast Slurpee', 'https://www.facebook.com/7Eleven/posts/10157310702513255'),
(14, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Vape Cup', 'null'),
(15, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Unseasoned Fries', 'https://twitter.com/checkersrallys/status/1112701156097036289'),
(30, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Super Dough Coffee Cup Holder', 'https://news.dunkindonuts.com/blog/spring-dunkin-donut-coffee-holder'),
(39, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'CBO: Chief Biscuit Officer', 'https://twitter.com/Hardees/status/1112656611141713921'),
(43, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Stacked Subs', 'https://twitter.com/jerseymikes/status/1112713726379974656'),
(50, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'McPickle', 'https://www.instagram.com/p/Bvr3W-AjUWd/'),
(50, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'McNugget Singles', 'https://www.instagram.com/mcdonaldscanada/p/BvtfACbn3fl/'),
(50, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Big Mac Flavored Smoothie', 'https://www.instagram.com/mcdonaldsde/p/BvtT11VBKjU/'),
(50, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Shake Sauce for Fries', 'https://www.instagram.com/p/BvtlBd4hxeo/'),
(56, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Cookie and Cremes Oreo', 'https://twitter.com/Oreo/status/1112779824450420736'),
(66, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Ravioli', 'https://www.facebook.com/poptarts/posts/10156937528035516'),
(68, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Red Licorice Straws', 'https://www.redlobster.com/news-press/press/2019/03/29/red-lobster-makes-sweet-move-to-replace-plastic-straws-with-red-licorice-straws-starting-summer-2019'),
(75, 454, 'Face 2 Face: April Food''s Day', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-454-face-2-face-april-foods-day/', 'Breadsticks leaving the menu', 'https://twitter.com/stonefiregrill/status/1112754055728820226'),
(37, 455, 'Fear-Sponging Material', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-455-fear-sponging-material/', 'Special Menu for 4/20', 'https://www.qsrmagazine.com/news/freshco-launches-cannabis-focused-menu'),
(81, 455, 'Fear-Sponging Material', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-455-fear-sponging-material/', 'Pretzel Bites', 'https://www.qsrmagazine.com/news/toppers-pizza-adds-pretzel-bites-value-menu'),
(14, 456, 'Good Happy Taste!!!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-456-good-happy-taste/', 'Rocky Mountain High: CheeseBurger Delight (CBD)', 'https://www.qsrmagazine.com/news/carl-s-jr-test-cbd-burger-denver-420'),
(25, 456, 'Good Happy Taste!!!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-456-good-happy-taste/', 'New Tagline: Happy Tastes Good', 'https://www.qsrmagazine.com/news/dairy-queen-unveils-new-tagline'),
(47, 458, 'Race Island: A Horse Show', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-458-race-island-horse-show/', 'Fruit Inspired Donuts', 'https://www.qsrmagazine.com/news/krispy-kreme-launch-fruit-inspired-doughnut-lineup'),
(50, 458, 'Race Island: A Horse Show', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-458-race-island-horse-show/', '"Worldwide Favorites"', 'https://www.qsrmagazine.com/menu-innovations/report-bringing-worldwide-favorites-menu'),
(40, 459, 'Face 2 Face: You Know, Like Eggs?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-459-face-2-face-you-know-like-eggs/', 'Cadbury Creme Egg Mayo', 'https://metro.co.uk/2019/04/03/heinz-creme-egg-mayo-wasnt-an-april-fool-you-can-actually-try-it-yourself-9103236/'),
(31, 460, 'Dr Praetorium''s Fudge-a-matorium', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-460-dr-praetoriums-fudge-matorium/', 'Idaho Debut', 'https://www.qsrmagazine.com/news/earl-sandwich-debuts-idaho'),
(38, 462, 'The Pork Doctor', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-462-pork-doctor/', '...GarfieldEATS exists', 'null'),
(7, 463, 'Stranger Creams', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-464-stranger-creams/', 'Stranger Things-Inspired Flavors', 'https://www.qsrmagazine.com/news/stranger-things-inspired-flavors-arrive-baskin-robbins'),
(25, 463, 'Stranger Creams', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-464-stranger-creams/', '"Box of Happy" Subscription Box', 'https://www.qsrmagazine.com/news/dairy-queen-unveils-lineup-box-happy-subscription-boxes'),
(45, 464, 'Face 2 Face: Peace with the Ground-Children', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-464-face-2-face-peace-ground-children/', 'SWEET LIGHTNING', 'https://www.prnewswire.com/news-releases/mtn-dew-introduces-sweet-lightning-available-exclusively-at-kfc--a-bold-new-beverage-to-pair-perfectly-with-the-colonels-11-herbs-and-spices-300865032.html'),
(47, 465, 'It''s Definitely Chodezilla', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-465-its-definitely-chodezilla/', 'One Giant Leap for Doughnut-kind', 'https://www.businesswire.com/news/home/20190617005034/en/Giant-Leap-Doughnut-Kind%21'),
(54, 465, 'It''s Definitely Chodezilla', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-465-its-definitely-chodezilla/', 'Brekky Burger', 'https://www.qsrmagazine.com/news/just-egg-partners-next-level-burger-create-brekky-burger'),
(62, 465, 'It''s Definitely Chodezilla', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-465-its-definitely-chodezilla/', 'Cheese Bites Pizza', 'https://www.qsrmagazine.com/news/pizza-hut-s-cheesy-bites-pizza-returns-limited-time'),
(5, 466, 'Food Train', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-466-food-train/', 'Meat Carrot', 'https://www.insider.com/arbys-meat-carrot-made-out-of-turkey-2019-6'),
(45, 466, 'Food Train', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-466-food-train/', 'Cheetos Sandwhich', 'https://www.eater.com/2019/6/20/18692813/kfc-cheetos-chicken-sandwich'),
(78, 470, 'Mama Freddy''s Turbo Spaghetti', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-470-mama-freddys-turbo-spaghetti/', 'Pop-up Hotel', 'https://www.prnewswire.com/news-releases/taco-bell-hotel-launching-august-2019---adding-a-spicy-twist-to-summer-travel-300851363.html'),
(61, 471, 'Face 2 Face: The Fraternity of Bones', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-471-face-2-face-fraternity-bones/', '...Did you see the Company Name?!?', 'https://www.victoriabuzz.com/2019/05/this-outrageously-kinky-ice-cream-store-is-coming-to-victoria-in-july/'),
(65, 472, 'Public Domain LASIK Voicemails', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-472-public-domain-lasik-voicemails/', 'Chicken Sandwich...sold at Sweet Dixie', 'https://www.qsrmagazine.com/news/popeyes-launches-new-chicken-sandwich-you-can-t-get-it-popeyes'),
(84, 472, 'Public Domain LASIK Voicemails', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-472-public-domain-lasik-voicemails/', '2 Million Nugget Giveaway', 'https://www.qsrmagazine.com/news/wendys-giving-away-2-million-nuggets-celebrate-spicy-return'),
(55, 473, 'Spooketti', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-473-spooketti/', 'Lifetime Pasta Pass', 'https://www.olivegarden.com/specials/never-ending-pasta-pass/lifetime-pass'),
(40, 475, 'Edchup', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-475-edchup/', 'Ed Sheeron Ketchup', 'https://www.foodandwine.com/news/ed-sheeran-heinz-ketchup-tattoo-bottle'),
(89, 477, 'Crash Bandicoot''s Wallet Chain', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-477-crash-bandicoots-wallet-chain/', 'Baked Pasta', 'https://www.qsrmagazine.com/news/your-pie-launches-baked-pasta-nationwide'),
(45, 478, 'The Sprite Slide, a Sprite Experience', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-478-the-sprite-slide-a-sprite-experience/', 'Doughnut Chicken Sandwhich', 'https://www.eater.com/2019/9/18/20872133/kfc-donut-chicken-sandwich'),
(62, 478, 'The Sprite Slide, a Sprite Experience', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-478-the-sprite-slide-a-sprite-experience/', 'Stuffed Cheez-It Pizza', 'https://www.eater.com/2019/9/17/20870362/pizza-hut-cheez-it-stuffed-pizza'),
(45, 479, 'Face 2 Face: A Spectral, Horny Build-A-Bear', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-479-face-2-face-a-spectral-horny-build-a-bear/', 'Doughnut Chicken Sandwhich (cont)', 'null'),
(35, 482, 'Face 2 Face: Big Stitch Energy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-482-face-2-face-big-stitch-energy/', 'Cranberry Turkey Burger and a Pumpkin Spice Shake', 'https://www.qsrmagazine.com/news/fatburger-adds-cranberry-turkeyburger-and-pumpkin-spice-shake'),
(78, 482, 'Face 2 Face: Big Stitch Energy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/episode-482-face-2-face-big-stitch-energy/', 'Taco Hero Contest', 'null'),
(12, 485, 'Face 2 Face: Haunted Munch Squad', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/485-face-2-face-haunted-munch-squad/', 'Ghost Whopper', 'https://www.qsrmagazine.com/news/burger-king-unveils-ghost-whopper-halloween'),
(1, 486, 'That''s So Hambone!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/486-thats-so-hambone/', 'Beyond Burnt Ends', 'https://www.4rsmokehouse.com/beyond-burnt-ends/'),
(88, 486, 'That''s So Hambone!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/486-thats-so-hambone/', 'Flamin Hot Cheetos Topping and Holiday menu', 'https://www.yogurt-land.com/news_posts/view/36/fire-up-the-holiday-season-with-yogurtland-and-cheetos-flamin-hot'),
(90, 487, 'Frasier Crane''s Anime Dreamscape', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-487-frasier-cranes-anime-dreamscape/', 'Jumanji-Theme''d Menu', 'https://www.qsrmagazine.com/news/zaxby-s-introduces-jumanji-themed-menu-items'),
(11, 488, 'Huff the Un-Foot', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-488-huff-the-un-foot/', 'Caroling Pizza Box', 'https://strategyonline.ca/2019/11/20/boston-pizza-delivers-a-caroling-pizza-box/'),
(32, 490, 'Ewdaddy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-490-ewdaddy/', 'Incredible Edibles', 'https://www.prnewswire.com/news-releases/edible-arrangements-debuts-incredible-edibles-product-line-300963109.html'),
(51, 490, 'Ewdaddy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-490-ewdaddy/', 'Space Jam Menu', 'https://urbanmatter.com/chicago/michael-jordan-steak-house-offers-limited-time-space-jam-menu/'),
(68, 490, 'Ewdaddy', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-490-ewdaddy/', 'Red Lobster Ugly Sweater', 'https://www.prnewswire.com/news-releases/red-lobster-releases-limited-edition-deliciously-ugly-sweaters-just-in-time-for-the-holidays-300963893.html'),
(73, 492, 'The Naming of 2020', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-492-the-naming-of-2020/', '99cent Alcoholic Beverages', 'https://www.kansas.com/news/business/biz-columns-blogs/carrie-rengers/article237086014.html'),
(78, 493, 'Face 2 Face: U Up?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-493-face-2-face-u-up/', 'Toasted Chedder Chalupa', 'null'),
(20, 495, 'Play Along at Home!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-495-play-along-at-home/', 'David McKillips is the new CEO', 'https://www.nrn.com/people/chuck-e-cheese-s-parent-cec-names-david-mckillips-ceo'),
(64, 495, 'Play Along at Home!', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-495-play-along-at-home/', 'Mr. Peanut DIES', 'https://ir.kraftheinzcompany.com/news-releases/news-release-details/mr-peanut-passes-away-104-years-old-sacrificing-himself-save'),
(62, 496, 'The Hyena Hole', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-496-the-hyena-hole/', 'Reward for First Set of Twins born on Super Bowl', 'https://www.qsrmagazine.com/news/pizza-hut-will-reward-first-set-twins-born-after-super-bowl'),
(10, 499, 'Right Down the Middle', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-499-right-down-the-middle/', 'Baby Back Rib Bouquet', 'https://www.qsrmagazine.com/news/boston-market-selling-baby-back-rib-bouquets-2999'),
(45, 501, 'Face 2 Face: Jeans-Washed Acid', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-501-face-2-face-jeans-washed-acid/', 'KFC and Crocs Bucket Clogs', 'https://www.prnewswire.com/news-releases/kfc-and-crocs-debut-bucket-clogs-at-new-yorks-biggest-week-in-fashion-301003512.html'),
(30, 502, 'American Psycho 2: The Squeakquel', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-502-american-psycho-2-the-squeakquel/', 'Snackin` Bacon', 'https://www.qsrmagazine.com/news/dunkin-adds-snackin-bacon-menu'),
(33, 502, 'American Psycho 2: The Squeakquel', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-502-american-psycho-2-the-squeakquel/', 'Bagel/Burrito Mashup', 'https://www.qsrmagazine.com/news/einstein-bros-launch-bagel-and-burrito-mash'),
(78, 503, 'How to Get Away with Pinkbelly', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-503-how-to-get-away-with-pinkbelly/', 'Triplelupa', 'https://www.prnewswire.com/news-releases/taco-bell-debuts-its-longest-shell-ever-with-the-triplelupa-the-ultimate-reinvention-of-the-fan-favorite-chalupa-301020190.html'),
(19, 504, 'The Nasty Buns', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-504-the-nasty-buns/', 'Virtual Hangout with Rob Gronkowski ', 'https://www.qsrmagazine.com/news/rob-gronkowski-join-chipotle-thursdays-virtual-hangout'),
(27, 505, 'Slippery When Voltron', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-505-slippery-when-voltron/', 'THE DOMINATOR', 'https://www.baltimoresun.com/news/bs-xpm-1993-04-30-1993120157-story.html'),
(10, 506, 'The Enchanted Horn of American Heroism', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-506-the-enchanted-horn-of-american-heroism/', 'Take-Home Easter Dinners', 'https://www.qsrmagazine.com/news/boston-market-serving-take-home-easter-dinner-options'),
(14, 506, 'The Enchanted Horn of American Heroism', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-506-the-enchanted-horn-of-american-heroism/', 'Family Bundles', 'https://www.qsrmagazine.com/news/carls-jr-hardees-add-family-bundles-menus'),
(86, 506, 'The Enchanted Horn of American Heroism', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-506-the-enchanted-horn-of-american-heroism/', 'Free Meals for Healthcare Workers', 'https://www.qsrmagazine.com/news/white-castle-give-healthcare-workers-free-meals'),
(90, 506, 'The Enchanted Horn of American Heroism', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-506-the-enchanted-horn-of-american-heroism/', 'Family Packs', 'https://www.qsrmagazine.com/news/zaxbys-introduces-family-packs-drive-thru-and-delivery'),
(40, 507, 'Dirtiest Dancing: Havana Nights', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-507-dirtiest-dancing-havana-nights/', 'Mystery EZ Squirt', 'null'),
(83, 507, 'Dirtiest Dancing: Havana Nights', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-507-dirtiest-dancing-havana-nights/', 'vampire.pizza', 'https://www.vampire.pizza/'),
(60, 508, 'Face 2 Face: The Pepsi Proposal', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-508-face-2-face-the-pepsi-proposal/', 'Crystal Pepsi Engagement Ring', 'null'),
(22, 509, 'The Grind Butler (Or: Grutler)', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-509-the-grind-butler-or-grutler/', 'Passion For Ice Cream', 'null'),
(5, 511, 'A Big Beautiful Buick Enclave', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-511-a-big-beautiful-buick-enclave/', 'Barry White does a Commerical', 'https://www.youtube.com/watch?v=992txS0WHZo&ab_channel=RewindMe'),
(26, 512, 'The Jabberjaw Affair', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-512-the-jabberjaw-affair/', 'Denny''s/Rockstar Collab', 'https://www.qsrmagazine.com/news/dennys-pairs-rockers-new-menu'),
(9, 513, 'Mother Cruncher', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-513-mother-cruncher/', 'Video Game Studio', 'null'),
(15, 513, 'Mother Cruncher', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-513-mother-cruncher/', 'Mother Cruncher Chicken Sandwhich', 'https://www.qsrmagazine.com/news/checkers-rallys-introduces-mother-cruncher-chicken-sandwich'),
(67, 514, 'Kickeo', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-514-kickeo/', 'Baconator Flavored Pringles', 'https://www.prnewswire.com/news-releases/limited-edition-pringles-flavor-packs-the-juicy-layers-of-a-wendys-baconator-into-one-crunchy-bite-301073207.html'),
(58, 516, 'Radical Gamer Facts', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-516-radical-gamer-facts/', 'Shaq-a-Roni Pizza', 'https://www.qsrmagazine.com/news/papa-johns-introduces-extra-large-shaq-roni-pizza'),
(7, 517, 'Pepperoni Prescription', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-517-pepperoni-prescription/', 'Bud Light Seltzer Pairings', 'https://news.baskinrobbins.com/blog/bud-light-seltzer-pairings'),
(78, 518, 'Pepperoni and Vicki', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-518-pepperoni-and-vicki/', 'Free Tacos if the Mir Station hits a Target in the South Pacific', 'http://www.spaceref.com/news/viewpr.html?pid=4152'),
(40, 519, 'The Grandma Tesseract', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-519-the-grandma-tesseract/', '"Heinz Creams"', 'https://www.chattingfood.com/post/heinz-creamz-kits'),
(6, 520, 'Genuine Clean Fauciballs', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-520-genuine-clean-fauciballs/', 'RADICAL SKADATTLE', 'https://www.globenewswire.com/news-release/2020/06/02/2042191/0/en/Big-Bang-New-Flavor-RADICAL-SKADATTLE.html'),
(45, 520, 'Genuine Clean Fauciballs', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-520-genuine-clean-fauciballs/', '3D Printing Meat', 'null'),
(59, 520, 'Genuine Clean Fauciballs', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-520-genuine-clean-fauciballs/', 'Chicken Tender Hand Spun Shake', 'https://www.orlandoweekly.com/Blogs/archives/2020/07/24/central-florida-pdq-locations-to-offer-milkshake-monday-containing-blended-chicken-tenders'),
(16, 521, 'Ah, The Soup Mess', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-522-ah-the-soup-mess/', 'Cheezit and Wine pairings', 'https://newsroom.kelloggcompany.com/2020-07-21-The-Pack-Is-Back-Cheez-It-R-White-Cheddar-And-Refreshing-House-Wine-Rose-Combine-For-Year-Two-Toast'),
(19, 522, 'The Open and Honest Heart of a Child''s Eyes', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-522-the-open-and-honest-heart-of-a-childs-eyes/', 'Tony Hawk Burrito', 'https://www.qsrmagazine.com/news/chipotle-launches-tony-hawk-burrito'),
(36, 523, 'Dad''s Fat Trash Sack', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-523-dads-fat-trash-sack/', 'Ghost Kitchen', 'https://www.qsrmagazine.com/news/fazolis-serving-deep-fried-wings-first-ghost-kitchen-atlanta'),
(72, 523, 'Dad''s Fat Trash Sack', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-523-dads-fat-trash-sack/', 'Pop-up store in NYC', 'https://sourpatchkids.com/store_nyc'),
(12, 524, 'Teen Beans', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-524-teen-beans/', 'Orders Printed on Masks', 'https://www.businessinsider.com/burger-king-belgium-allows-customers-to-order-using-facemasks-2020-8#:~:text=Burger%20King%20is%20giving%20250,their%20order%20printed%20on%20it.'),
(45, 524, 'Teen Beans', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-524-teen-beans/', 'No More Finger-Lickin Good Slogan', 'https://www.businessinsider.com/kfc-pausing-finger-lickin-good-motto-due-to-hygienic-implications-2020-8'),
(78, 524, 'Teen Beans', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-524-teen-beans/', 'Menu gets trimmed', 'https://www.qsrmagazine.com/fast-food/taco-bell-trim-menu-nationwide-august-13'),
(74, 525, 'Problems Related to Me Falling Down the Stairs', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-525-problems-related-to-me-falling-down-the-stairs/', '1-833-GET-FALL', 'https://www.qsrmagazine.com/news/starbucks-pumpkin-spice-latte-returns-along-fall-lineup'),
(69, 526, 'Why Not a Wizard?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-526-why-not-a-wizard/', 'Snack Cakes', 'https://www.globenewswire.com/news-release/2020/09/02/2087767/0/en/Reese-s-Brand-Saves-Your-Morning-With-New-Reese-s-Snack-Cakes.html'),
(78, 526, 'Why Not a Wizard?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-526-why-not-a-wizard/', 'Mexican Pizza Removed', 'https://www.qsrmagazine.com/fast-food/taco-bell-remove-mexican-pizza-final-2020-menu-revamp'),
(87, 526, 'Why Not a Wizard?', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-526-why-not-a-wizard/', 'Cheesy Ooze Fest', 'https://www.prnewswire.com/news-releases/wienerschnitzel-announces-lineup-for-new-cheesy-ooze-fest-event-301121375.html'),
(42, 527, 'HORSEWAR', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-527-horsewar/', 'Golden Ticket Treasure Hunt', 'null'),
(64, 527, 'HORSEWAR', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-527-horsewar/', 'Baby Nut Turns 21', 'https://adage.com/article/news/planters-unveils-natural-light-collab-baby-nuts-21st-birthday/2275896'),
(46, 529, 'Throw Me In the Dumpster Behind the Applebees When I Die', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-529-throw-me-in-the-dumpster-behind-the-applebees-when-i-die/', 'Pumpkin Spice KD', 'https://quickbitenews.com/article/hamilton/pumpkin-spice-kd-coming-to-canada-this-fall/'),
(68, 529, 'Throw Me In the Dumpster Behind the Applebees When I Die', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-529-throw-me-in-the-dumpster-behind-the-applebees-when-i-die/', 'DEW-Garita', 'https://www.redlobster.com/news-press/press/2020/09/15/red-lobster-and-pepsico-kick-off-new-relationship-with-thedew-garita---the-first-official-mtn-dew-cocktail'),
(80, 529, 'Throw Me In the Dumpster Behind the Applebees When I Die', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-529-throw-me-in-the-dumpster-behind-the-applebees-when-i-die/', 'Free Pumpkins', 'https://www.qsrmagazine.com/news/tim-hortons-giving-away-pumpkins-beverage-orders'),
(45, 531, 'Mighty Morphin'' Grown-Up Power Rangers', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-531-mighty-morphin-grown-up-power-rangers/', 'KFCharcuterie', 'https://www.qsrmagazine.com/news/kfc-introduce-new-signature-dipping-sauce-nationwide-october-12'),
(29, 532, 'The Spooky Box', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-532-the-spooky-box/', 'Spooky Box', 'https://www.qsrmagazine.com/news/duck-donuts-spooky-box-returns-halloween'),
(30, 532, 'The Spooky Box', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-532-the-spooky-box/', 'Ghost Pepper Donut', 'https://www.qsrmagazine.com/news/dunkin-gets-spicy-new-ghost-pepper-donut'),
(33, 533, 'Butterbobs n'' Batteries', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-533-butterbobs-n-batteries/', 'Party Bagels!', 'https://www.qsrmagazine.com/news/einstein-bros-adding-new-party-bagels'),
(40, 533, 'Butterbobs n'' Batteries', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-533-butterbobs-n-batteries/', 'Tomato Blood Ketchup', 'https://www.businesswire.com/news/home/20201023005050/en/Trick-or-Treating-Is-Going-to-Look-Different-This-Year-So-HEINZ-Is-Giving-Families-a-Spooky-Way-to-Celebrate-With-Launch-of-New-Tomato-Blood-Ketchup'),
(35, 534, 'The Hang-In-There Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-534-the-hang-in-there-burger/', 'Hang-In-There Burger', 'https://www.qsrmagazine.com/news/fatburger-introduces-hang-there-burger'),
(49, 534, 'The Hang-In-There Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-534-the-hang-in-there-burger/', 'Santa''s Yumnut', 'https://twitter.com/marksandspencer/status/1324300740035313666'),
(74, 534, 'The Hang-In-There Burger', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-534-the-hang-in-there-burger/', 'Carry the Merry', 'https://stories.starbucks.com/stories/2020/holiday-season-at-starbucks/'),
(47, 535, 'Ethical Joker Termination', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-535-ethical-joker-termination/', 'Caramel Glaze', 'https://www.qsrmagazine.com/news/krispy-kreme-introduces-new-caramel-glaze'),
(53, 535, 'Ethical Joker Termination', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-535-ethical-joker-termination/', 'Cook Book', 'https://www.prnewswire.com/news-releases/mtn-dew-pays-homage-to-fans-with-first-ever-cookbook-for-brands-80th-birthday-301169739.html'),
(53, 535, 'Ethical Joker Termination', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-535-ethical-joker-termination/', 'Baja Blast "Dye Hard" Tee', 'https://store.mountaindew.com/products/baja-dye-hard-tee'),
(45, 538, 'Showgaze Mopytones', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-538-shoegaze-mopeytones/', 'KFC/Lifetime Original Channel Movie', 'https://www.qsrmagazine.com/news/kfc-and-lifetime-air-original-movie-mario-lopez-colonel-sanders'),
(50, 539, 'Quantum Beef', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-539-quantum-beef/', 'The Grinch favorite menu', 'https://www.prnewswire.com/news-releases/holiday-cheer-arrives-at-mcdonalds-as-fans-can-enjoy-the-favorite-menu-items-of-santa-claus-the-grinch-and-more-301190576.html'),
(12, 541, 'Angles in the Ragnarok', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-541-angels-in-the-ragnarok/', 'New Dollar Menu', 'https://www.qsrmagazine.com/fast-food/burger-king-offer-new-dollar-menu'),
(48, 541, 'Angles in the Ragnarok', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-541-angels-in-the-ragnarok/', 'Hangover Krystal', 'https://www.qsrmagazine.com/news/hangover-krystal-returns-popular-demand-169'),
(58, 541, 'Angles in the Ragnarok', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-541-angels-in-the-ragnarok/', 'Epic Stuffed Crust', 'https://www.qsrmagazine.com/news/papa-johns-launches-new-epic-stuffed-crust'),
(78, 541, 'Angles in the Ragnarok', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-541-angels-in-the-ragnarok/', 'Nacho Fries RETURN', 'https://www.qsrmagazine.com/news/taco-bells-famed-nacho-fries-return-holidays'),
(82, 541, 'Angles in the Ragnarok', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-541-angels-in-the-ragnarok/', 'Mardi Gras menu', 'https://www.qsrmagazine.com/news/tropical-smoothie-cafe-introduces-mardi-gras-themed-menu-new-year'),
(20, 543, 'Charles Equality Cheese', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-543-charles-equality-cheese/', 'Guess what E. Stands For', 'https://twitter.com/ChuckECheese/status/1347654422080458754'),
(63, 543, 'Charles Equality Cheese', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-543-charles-equality-cheese/', 'Pizza Inn Takes a Bold Stance on Election Reform', 'https://twitter.com/PizzaInn_Inc/status/1346539477242699781'),
(76, 544, 'Quantum Cheez-Its', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-544-quantum-cheez-its/', 'Subway Tuna Lawsuit', 'https://www.grubstreet.com/2021/01/subway-tuna-lawsuit.html'),
(50, 547, 'Chili Wonka', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-547-chili-wonka/', 'Shamrock Shake is BACK', 'https://www.qsrmagazine.com/news/mcdonalds-famed-shamrock-shake-return-february-15'),
(78, 547, 'Chili Wonka', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-547-chili-wonka/', 'Cravings Box for the People', 'https://www.qsrmagazine.com/news/taco-bells-new-5-build-your-own-cravings-box-people'),
(84, 547, 'Chili Wonka', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-547-chili-wonka/', 'People Talking About Breakfast in a Pandemic', 'https://www.qsrmagazine.com/exclusives/how-wendys-got-people-talking-about-breakfast-pandemic'),
(57, 548, 'Jeans All The Way Down', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-548-jeans-all-the-way-down/', 'Bread Bowl Gloves', 'null'),
(30, 550, 'The Spider-Man Truth', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-550-the-spider-man-truth/', 'Avocado Toast', 'https://www.qsrmagazine.com/news/dunkin-adds-avocado-toast-menu'),
(78, 550, 'The Spider-Man Truth', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-550-the-spider-man-truth/', 'Crispy Chicken Sandwich Taco', 'https://www.qsrmagazine.com/news/taco-bell-starts-testing-crispy-chicken-sandwich-taco'),
(53, 551, 'Non-Euclidian Meat Cone', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/non-euclidian-meat-cone/', 'Bob Ross Deepfakes', 'https://www.prnewswire.com/news-releases/mtn-dew-debuts-lost-episode-of-bob-ross-painting-tutorial-to-inspire-creativity-301237383.html'),
(3, 552, 'Introducing Fredo Cooljazz', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-552-introducing-fredo-cooljazz/', 'Cod Sliders Back in Time for Lent', 'https://www.qsrmagazine.com/news/aws-cod-sliders-return-time-lent'),
(13, 552, 'Introducing Fredo Cooljazz', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-552-introducing-fredo-cooljazz/', 'SWAG Burger', 'https://www.qsrmagazine.com/news/burgerfi-wants-start-battle-spicy-burger'),
(90, 552, 'Introducing Fredo Cooljazz', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-552-introducing-fredo-cooljazz/', 'Chicken Wars - Signature Sandwich National Rollout', 'https://www.qsrmagazine.com/news/zaxbys-signature-sandwich-preps-national-launch'),
(67, 553, 'The Planet''s Dying, Pringle', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-553-the-planets-dying-pringle/', 'Halo-Theme''d Moa Burger Pringles', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-553-the-planets-dying-pringle/'),
(47, 554, 'Tub Pumpkin', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-554-tub-pumpkin/', 'Free Donuts for The Vaccinated', 'https://www.krispykreme.com/promos/vaccineoffer'),
(60, 554, 'Tub Pumpkin', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-554-tub-pumpkin/', 'Peepsi', 'https://www.prnewswire.com/news-releases/pepsi-drops-limited-edition-pepsi-x-peeps-marshmallow-cola-for-spring-301256012.html'),
(3, 555, 'Come Get a Sack', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-555-come-get-a-sack/', 'It''s going to Take More than a Pandemic to Stop A&W', 'https://www.qsrmagazine.com/exclusives/its-going-take-more-pandemic-stop-aw'),
(86, 555, 'Come Get a Sack', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-555-come-get-a-sack/', 'Birthday Cake on a Stick', 'https://www.qsrmagazine.com/news/white-castle-launches-birthday-cake-stick-dessert'),
(34, 556, 'New Virtual Wing Concept', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-556-new-virtual-wing-concept/', 'Companion Cookbook...for humans', 'https://www.prnewswire.com/news-releases/fancy-feast-releases-petites-feast-cookbook--a-recipe-guide-for-humans-inspired-by-their-new-single-serve-entrees-for-cats-301261285.html'),
(36, 556, 'New Virtual Wing Concept', 'https://maximumfun.org/episodes/my-brother-my-brother-and-me/mbmbam-556-new-virtual-wing-concept/', 'Chicken Wings Rollout', 'https://www.qsrmagazine.com/news/fazolis-rolls-highly-anticipated-wings-systemwide');

COMMIT;